#!/bin/bash

cd ../bin

./rsa-sign -k ../test/test-rsa-sig-secret-key -m ../test/test-rsa-sig-message -s ../test/test-rsa-sig-signature

printf "Valid message output: "
./rsa-validate -k ../test/test-rsa-sig-public-key -m ../test/test-rsa-sig-message -s ../test/test-rsa-sig-signature

printf "Invalid message output: "
./rsa-validate -k ../test/test-rsa-sig-public-key -m ../test/test-rsa-sig-message -s ../test/test-rsa-sig-bad-signature
