#!/bin/bash

cd ../../bin

SAMPLE_KEY_DIR=../test/sample-keys
SAMPLE_DATA_DIR=../test/sample-data
AES_KEY=$SAMPLE_KEY_DIR/aes-key
MESSAGE_FILE=$SAMPLE_DATA_DIR/cbcmac-tag-message
TAG_FILE=$SAMPLE_DATA_DIR/cbcmac-validate-message-tag
BAD_TAG_FILE=$SAMPLE_DATA_DIR/cbcmac-validate-bad-message-tag

./cbcmac-tag -k $AES_KEY -m $MESSAGE_FILE -t $TAG_FILE

printf "Valid tag output: "
./cbcmac-validate -k $AES_KEY -m $MESSAGE_FILE -t $TAG_FILE

printf "Invalid tag output: "
./cbcmac-validate -k $AES_KEY -m $MESSAGE_FILE -t $BAD_TAG_FILE
