#!/bin/bash

cd ../bin

printf "rsa-sign\n"
printf "========\n"
./rsa-sign -k test-key-file -m test-message-file -s test-signature-file
printf "\n"

printf "rsa-validate\n"
printf "============\n"
./rsa-validate -k test-key-file -m test-message-file -s test-signature-file
printf "\n"

printf "cbcmac-tag\n"
printf "==========\n"
./cbcmac-tag -k test-key-file -m test-message-file -t test-output-file
printf "\n"

printf "cbcmac-validate\n"
printf "===============\n"
./cbcmac-validate -k test-key-file -m test-message-file -t test-output-file
printf "\n"

printf "lock\n"
printf "====\n"
./lock -d test-lock-directory -p test-action-public-key -r test-action-private-key -vk test-validating-public-key
printf "\n"

printf "unlock\n"
printf "======\n"
./unlock -d test-lock-directory -p test-action-public-key -r test-action-private-key -vk test-validating-public-key
printf "\n"
